# Generated by Django 5.2.4 on 2025-08-13 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(max_length=5)),
                ('esta_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('capacidad_asientos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('OCUPADO', 'Ocupado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=20)),
                ('asiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_aerolinea.asiento')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aerolinea.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('duracion_minutos', models.IntegerField()),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aerolinea.avion')),
            ],
        ),
        migrations.AddField(
            model_name='asiento',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aerolinea.vuelo'),
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('vuelo', 'numero_asiento')},
        ),
    ]
