# Generated by Django 5.2.5 on 2025-08-13 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'ordering': ['numero_asiento']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_reserva']},
        ),
        migrations.AlterModelOptions(
            name='vuelo',
            options={'ordering': ['fecha_salida', 'hora_salida']},
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='fecha_llegada',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='hora_llegada',
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_boleto',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='gestion_aerolinea.vuelo'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='capacidad_asientos',
            field=models.IntegerField(help_text='Número total de asientos en el avión.'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='asiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gestion_aerolinea.asiento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('CHECKED_IN', 'Check-in Realizado')], default='RESERVADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='gestion_aerolinea.pasajero'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='avion',
            field=models.ForeignKey(help_text='Avión asignado a este vuelo. No se podrá eliminar el avión si tiene vuelos asignados.', on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='gestion_aerolinea.avion'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='duracion_minutos',
            field=models.IntegerField(help_text='Duración estimada del vuelo en minutos.'),
        ),
    ]
