# Generated by Django 5.2.5 on 2025-08-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aerolinea', '0002_alter_asiento_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='capacidad_asientos',
            field=models.IntegerField(),
        ),
    ]
