# Generated by Django 5.2.4 on 2025-08-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='aviones/'),
        ),
    ]
